docs: check if ignored header files actually exist
To prevent accumulating stale entries in IGNORE_HFILE, add a hook
target that looks for the files, and bails the doc build if an entry
no longer exists.

diff --git a/docs/reference/ytstenut/Makefile.am b/docs/reference/ytstenut/Makefile.am
--- a/docs/reference/ytstenut/Makefile.am
+++ b/docs/reference/ytstenut/Makefile.am
@@ -52,7 +52,6 @@ EXTRA_HFILES=
 # Header files to ignore when scanning. Use base file name, no paths
 # e.g. IGNORE_HFILES=gtkdebug.h gtkintl.h
 IGNORE_HFILES = \
-  empathy-tp-file.h \
   ytstenut-internal.h \
   yts-adapter-factory.h \
   yts-client-internal.h \
@@ -133,5 +132,23 @@ if BUILD_GTK_DOC
 #TESTS_ENVIRONMENT = cd $(srcsrc) &&
 #TESTS = $(GTKDOC_CHECK)
 endif
+
+# This is a hack to prevent the ignores list from containing stale entries.
+# Check if any of them are no more existant, and if so, bail out.
+if ENABLE_GTK_DOC
+HTML_BUILD_STAMP += check-ignores.stamp
+CLEANFILES += check-ignores.stamp
+endif
+
+check-ignores.stamp:
+	$(AM_V_GEN) b=`tput bold` && \
+	n=`tput sgr0` && \
+	for f in $(IGNORE_HFILES); do \
+		if [ "`find $(DOC_SOURCE_DIR) -name $${f}`" = "" ]; then \
+			echo "$${b}Error:  $${f} is ignored but not found anyway.$${n}"; \
+			exit 1; \
+		fi \
+	done
+	@touch $@
 
 -include $(top_srcdir)/git.mk
